# German translations for vigilo-connector.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-connector
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-connector 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 12:16+0100\n"
"PO-Revision-Date: 2010-11-19 12:16+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector/client.py:48
msgid "Authentication failure."
msgstr ""

#: src/vigilo/connector/client.py:49
msgid "Authentication failed:"
msgstr ""

#: src/vigilo/connector/client.py:53 src/vigilo/connector/client.py:54
msgid "Server does not support TLS encryption."
msgstr ""

#: src/vigilo/connector/converttoxml.py:42
msgid "Got one-to-one message"
msgstr "One-to-one Nachricht vorhanden"

#: src/vigilo/connector/converttoxml.py:47
msgid "Got empty line"
msgstr "Leere Zeile vorhanden"

#: src/vigilo/connector/converttoxml.py:49
msgid "Got 'event' message"
msgstr "'Ereignis'-Nachricht vorhanden"

#: src/vigilo/connector/converttoxml.py:52
msgid "Got 'perf' message"
msgstr "'perf' Nachricht vorhanden"

#: src/vigilo/connector/converttoxml.py:55
msgid "Got 'downtime' message"
msgstr "'Downtime'-Nachricht vorhanden"

#: src/vigilo/connector/converttoxml.py:58
msgid "Got 'command' message"
msgstr "'Befehl'-Nachricht vorhanden"

#: src/vigilo/connector/converttoxml.py:61
#: src/vigilo/connector/converttoxml.py:68
#: src/vigilo/connector/converttoxml.py:74
#, python-format
msgid "Unknown/malformed message type: '%s'"
msgstr "Unbekannter/fehlerhafter Nachrichtentyp: '%s'"

#: src/vigilo/connector/converttoxml.py:70
#, python-format
msgid "Converted to: %s"
msgstr "Umgewandelt in: %s"

#: src/vigilo/connector/converttoxml.py:78
#, python-format
msgid "Got malformed message: %s"
msgstr "Fehlerhafte Nachricht: %s vorhanden"

#: src/vigilo/connector/main.py:65
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht gefunden"

#: src/vigilo/connector/main.py:70
#, python-format
msgid "Directory not readable: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht lesbar"

#: src/vigilo/connector/main.py:75
#, python-format
msgid "Directory not writable: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht überschreibbar"

#: src/vigilo/connector/main.py:80
#, python-format
msgid "Directory not executable: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht ausführbar"

#: src/vigilo/connector/nodetoqueuefw.py:91
msgid "Incoming message is too big to be stored in the queue, dropping it."
msgstr ""
"Eingehende Nachricht ist zu groß, um in der Warteschlange gespeichert zu "
"werden, abbrechen."

#: src/vigilo/connector/nodetoqueuefw.py:96
#, python-format
msgid "The queue is full, dropping incoming XML message! (%s)"
msgstr ""
"Die Warteschlange ist voll, eingehende XML Nachricht wird abgebrochen! "
"(%s)"

#: src/vigilo/connector/nodetosocketfw.py:43
#: src/vigilo/connector/sockettonodefw.py:131
msgid "Connected to the XMPP bus"
msgstr "Mit XMPP-Bus verbunden"

#: src/vigilo/connector/nodetosocketfw.py:120
msgid ""
"Message impossible to forward (socket not connected), the message is "
"stored for later reemission"
msgstr ""
"Nachricht kann nicht weitergeleitet werden (Socket nicht verbunden),  "
"Nachricht wird gespeichert und später erneut gesendet"

#: src/vigilo/connector/nodetosocketfw.py:146
#, python-format
msgid "Chat message to forward: '%s'"
msgstr "Chat Nachricht zur Weiterleitung: '%s'"

#: src/vigilo/connector/nodetosocketfw.py:175
#, python-format
msgid "Message from BUS to forward: %s"
msgstr "Nachricht von BUS zur Weiterleitung: %s"

#: src/vigilo/connector/queuetonodefw.py:81
#, python-format
msgid "Error callback in consumeQueue(): %s"
msgstr "Fehler-Rückruf in consumeQueue(): %s"

#: src/vigilo/connector/queuetonodefw.py:101
msgid "Received request to shutdown"
msgstr "Anforderung zum Herunterfahren erhalten "

#: src/vigilo/connector/queuetonodefw.py:109
msgid "Item is None in consumeQueue, this should never happen!"
msgstr "Element ist Keine in consumeQueue, dies sollte nie  vorkommen!"

#: src/vigilo/connector/queuetonodefw.py:118
msgid "Stopping QueueToNodeForwarder."
msgstr "WarteschlangeToNodeForwarder beendet."

#: src/vigilo/connector/sockettonodefw.py:109
#, python-format
msgid "Received message: %r"
msgstr "Nachricht: %r erhalten"

#: src/vigilo/connector/sockettonodefw.py:152
#: src/vigilo/connector/sockettonodefw.py:196
#, python-format
msgid ""
"Message from Socket impossible to forward (no connection to XMPP server),"
" the message is stored for later reemission (%s)"
msgstr ""
"Nachricht aus Socket kann nicht weitergeleitet werden (keine Verbindung "
"mit dem XMPP-Server), die Nachricht wird gespeichert und später erneut "
"gesendet (%s)"

#: src/vigilo/connector/sockettonodefw.py:172
#, python-format
msgid ""
"Unable to forward the message (%(error)r), it has been stored for later "
"retransmission (%(xml_src)s)"
msgstr ""
"Die Nachricht (%(error)r) kann nicht weitergeleitet werden, wird "
"gespeichert und später erneut gesendet (%(xml_src)s)"

#: src/vigilo/connector/sockettonodefw.py:184
#, python-format
msgid "No destination node configured for messages of type '%s'. Skipping."
msgstr "Kein Zielknoten für Nachrichten vom Typ '%s' konfiguriert. Überspringen."

#: src/vigilo/connector/store.py:111
msgid "The database is locked"
msgstr "Die Datenbank ist gesperrt"

#: src/vigilo/connector/store.py:116
#, python-format
msgid "Some operational error occured. Original error message was: %s"
msgstr "Bedienungsfehler. Ursprüngliche Fehlermeldung: %s"

#: src/vigilo/connector/store.py:125
#, python-format
msgid "Some error occured. Original error message was: %s"
msgstr "Fehler. Ursprüngliche Fehlermeldung: %s"

