# English translations for vigilo-connector.
# Copyright (C) 2011 ORGANIZATION
# This file is distributed under the same license as the vigilo-connector
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-connector 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2011-03-22 10:50+0100\n"
"PO-Revision-Date: 2011-03-22 10:50+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector/client.py:67
#, python-format
msgid "Authentication failure: %s"
msgstr "Authentication failure: %s"

#: src/vigilo/connector/client.py:72 src/vigilo/connector/client.py:73
msgid "Server does not support TLS encryption."
msgstr "Server does not support TLS encryption."

#: src/vigilo/connector/client.py:139
msgid ""
"The \"watched_topics\" option has now been renamed into "
"\"subscriptions\". Please update your configuration file."
msgstr ""
"The \"watched_topics\" option has now been renamed into "
"\"subscriptions\". Please update your configuration file."

#: src/vigilo/connector/converttoxml.py:54
#: src/vigilo/connector/converttoxml.py:61
#: src/vigilo/connector/converttoxml.py:67
#, python-format
msgid "Unknown/malformed message type: '%s'"
msgstr "Unknown/malformed message type: '%s'"

#: src/vigilo/connector/converttoxml.py:71
#, python-format
msgid "Got malformed message: %s"
msgstr "Got malformed message: %s"

#: src/vigilo/connector/forwarder.py:32
msgid "no connection"
msgstr "no connection"

#: src/vigilo/connector/forwarder.py:36
msgid "no connection to the XMPP server"
msgstr "no connection to the XMPP server"

#: src/vigilo/connector/forwarder.py:97
msgid "Connected to the XMPP bus"
msgstr "Connected to the XMPP bus"

#: src/vigilo/connector/forwarder.py:116
#, python-format
msgid "Lost connection to the XMPP bus (reason: %s)"
msgstr "Lost connection to the XMPP bus (reason: %s)"

#: src/vigilo/connector/forwarder.py:148
#, python-format
msgid "Unable to forward the message (%(reason)s)"
msgstr "Unable to forward the message (%(reason)s)"

#: src/vigilo/connector/forwarder.py:154
msgid ". it has been stored for later retransmission"
msgstr ". it has been stored for later retransmission"

#: src/vigilo/connector/forwarder.py:227
#, python-format
msgid "Batch sent, waiting for %d replies from the bus"
msgstr "Batch sent, waiting for %d replies from the bus"

#: src/vigilo/connector/forwarder.py:244
#, python-format
msgid "Error trying to save a message to the backup database: %s"
msgstr "Error trying to save a message to the backup database: %s"

#: src/vigilo/connector/forwarder.py:423
#, python-format
msgid "No destination node configured for messages of type '%s'. Skipping."
msgstr "No destination node configured for messages of type '%s'. Skipping."

#: src/vigilo/connector/main.py:39
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Directory not found: '%(dir)s'"

#: src/vigilo/connector/main.py:44
#, python-format
msgid "Directory not readable: '%(dir)s'"
msgstr "Directory not readable: '%(dir)s'"

#: src/vigilo/connector/main.py:49
#, python-format
msgid "Directory not writable: '%(dir)s'"
msgstr "Directory not writable: '%(dir)s'"

#: src/vigilo/connector/main.py:54
#, python-format
msgid "Directory not executable: '%(dir)s'"
msgstr "Directory not executable: '%(dir)s'"

#: src/vigilo/connector/nodetoqueuefw.py:59
msgid "Incoming message is too big to be stored in the queue, dropping it."
msgstr "Incoming message is too big to be stored in the queue, dropping it."

#: src/vigilo/connector/nodetoqueuefw.py:64
#, python-format
msgid "The queue is full, dropping incoming XML message! (%s)"
msgstr "The queue is full, dropping incoming XML message! (%s)"

#: src/vigilo/connector/nodetosocketfw.py:24
msgid "socket not connected"
msgstr "socket not connected"

#: src/vigilo/connector/options.py:13
msgid "Choose the service name"
msgstr "Choose the service name"

#: src/vigilo/connector/options.py:14
msgid "Load this settings.ini file"
msgstr "Load this settings.ini file"

#: src/vigilo/connector/options.py:25
msgid "The configuration file does not exist"
msgstr "The configuration file does not exist"

#: src/vigilo/connector/presence.py:95
msgid "Queue size too high! Switching presence to unavailable."
msgstr "Queue size too high! Switching presence to unavailable."

#: src/vigilo/connector/presence.py:136
#, python-format
msgid ""
"Another instance of %(user)s@%(host)s has priority %(priority)d ! (me: "
"%(me)s, other: %(other)s)"
msgstr ""
"Another instance of %(user)s@%(host)s has priority %(priority)d ! (me: "
"%(me)s, other: %(other)s)"

#: src/vigilo/connector/queuetonodefw.py:83
msgid "Received request to shutdown"
msgstr "Received request to shutdown"

#: src/vigilo/connector/queuetonodefw.py:88
msgid "Item is None in consumeQueue, this should never happen!"
msgstr "Item is None in consumeQueue, this should never happen!"

#: src/vigilo/connector/queuetonodefw.py:93
msgid "Stopping QueueToNodeForwarder."
msgstr "Stopping QueueToNodeForwarder."

#: src/vigilo/connector/status.py:124
#, python-format
msgid "Stats for %(service)s: %(name)s = %(value)s"
msgstr "Stats for %(service)s: %(name)s = %(value)s"

#: src/vigilo/connector/store.py:166 src/vigilo/connector/store.py:261
#, python-format
msgid "Could not fill the output buffer: %s"
msgstr "Could not fill the output buffer: %s"

#: src/vigilo/connector/store.py:206
#, python-format
msgid "Could not VACUUM the database: %s"
msgstr "Could not VACUUM the database: %s"

