# English translations for vigilo-connector.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-connector
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-connector 2.0.0\n"
"Report-Msgid-Bugs-To: contact@projet-vigilo.org\n"
"POT-Creation-Date: 2010-04-23 16:00+0200\n"
"PO-Revision-Date: 2010-04-23 16:02+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector/converttoxml.py:37
msgid "Got one-to-one message"
msgstr "Got one-to-one message"

#: src/vigilo/connector/converttoxml.py:42
msgid "Got empty line"
msgstr "Got empty line"

#: src/vigilo/connector/converttoxml.py:44
msgid "Got 'event' message"
msgstr "Got 'event' message"

#: src/vigilo/connector/converttoxml.py:47
msgid "Got 'perf' message"
msgstr "Got 'perf' message"

#: src/vigilo/connector/converttoxml.py:50
msgid "Got 'downtime' message"
msgstr "Got 'downtime' message"

#: src/vigilo/connector/converttoxml.py:53
msgid "Got 'command' message"
msgstr "Got 'command' message"

#: src/vigilo/connector/converttoxml.py:56
#: src/vigilo/connector/converttoxml.py:63
#: src/vigilo/connector/converttoxml.py:69
#, python-format
msgid "Unknown/malformed message type: '%s'"
msgstr "Unknown/malformed message type: '%s'"

#: src/vigilo/connector/converttoxml.py:73
#, python-format
msgid "Got malformed message: %s"
msgstr "Got malformed message: %s"

#: src/vigilo/connector/main.py:65
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Directory not found: '%(dir)s'"

#: src/vigilo/connector/main.py:70
#, python-format
msgid "Directory not readable: '%(dir)s'"
msgstr "Directory not readable: '%(dir)s'"

#: src/vigilo/connector/main.py:75
#, python-format
msgid "Directory not writable: '%(dir)s'"
msgstr "Directory not writable: '%(dir)s'"

#: src/vigilo/connector/main.py:80
#, python-format
msgid "Directory not executable: '%(dir)s'"
msgstr "Directory not executable: '%(dir)s'"

#: src/vigilo/connector/nodetoqueuefw.py:91
msgid "Incoming message is too big to be stored in the queue, dropping it."
msgstr "Incoming message is too big to be stored in the queue, dropping it."

#: src/vigilo/connector/nodetoqueuefw.py:96
#, python-format
msgid "The queue is full, dropping incoming XML message! (%s)"
msgstr "The queue is full, dropping incoming XML message! (%s)"

#: src/vigilo/connector/nodetosocketfw.py:43
msgid "ConnectionInitialized"
msgstr "ConnectionInitialized"

#: src/vigilo/connector/nodetosocketfw.py:120
msgid ""
"Message impossible to forward (socket not connected), the message is "
"stored for later reemission"
msgstr ""
"Message impossible to forward (socket not connected), the message is "
"stored for later reemission"

#: src/vigilo/connector/nodetosocketfw.py:146
#, python-format
msgid "Chat message to forward: '%s'"
msgstr "Chat message to forward: '%s'"

#: src/vigilo/connector/nodetosocketfw.py:175
#, python-format
msgid "Message from BUS to forward: %s"
msgstr "Message from BUS to forward: %s"

#: src/vigilo/connector/queuetonodefw.py:81
#, python-format
msgid "Error callback in consumeQueue(): %s"
msgstr "Error callback in consumeQueue(): %s"

#: src/vigilo/connector/queuetonodefw.py:101
msgid "Received request to shutdown"
msgstr "Received request to shutdown"

#: src/vigilo/connector/queuetonodefw.py:109
msgid "Item is None in consumeQueue, this should never happen!"
msgstr "Item is None in consumeQueue, this should never happen!"

#: src/vigilo/connector/queuetonodefw.py:118
msgid "Stopping QueueToNodeForwarder."
msgstr "Stopping QueueToNodeForwarder."

#: src/vigilo/connector/sockettonodefw.py:109
#, python-format
msgid "Received message: %r"
msgstr "Received message: %r"

#: src/vigilo/connector/sockettonodefw.py:152
#: src/vigilo/connector/sockettonodefw.py:195
#, python-format
msgid ""
"Message from Socket impossible to forward (no connection to XMPP server),"
" the message is stored for later reemission (%s)"
msgstr ""
"Message from Socket impossible to forward (no connection to XMPP server),"
" the message is stored for later reemission (%s)"

#: src/vigilo/connector/sockettonodefw.py:172
#, python-format
msgid ""
"Unable to forward the message (%(error)r), it has been stored for later "
"retransmission (%(xml_src)s)"
msgstr ""
"Unable to forward the message (%(error)r), it has been stored for later "
"retransmission (%(xml_src)s)"

#: src/vigilo/connector/sockettonodefw.py:184
#, python-format
msgid "No destination node configured for messages of type '%s'. Skipping."
msgstr "No destination node configured for messages of type '%s'. Skipping."

#: src/vigilo/connector/store.py:111
msgid "The database is locked"
msgstr "The database is locked"

#: src/vigilo/connector/store.py:116
#, python-format
msgid "Some operational error occured. Original error message was: %s"
msgstr "Some operational error occured. Original error message was: %s"

#: src/vigilo/connector/store.py:125
#, python-format
msgid "Some error occured. Original error message was: %s"
msgstr "Some error occured. Original error message was: %s"

